---
title: "cascading_matching"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{cascading_matching}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

`codexplor::get_text_network_from_files()` offers successive text-researches, with a pattern searched that is changed dynamically between the 1st and the 2nd research, depending on the matches from the 1st research. In other terms, each iteration will extract text according to a 1st pattern => and create a 2nd pattern dynamically with the extracted text, in order to use it as the next pattern searched for. The number of successive researches iteration is the depth of this cascading research.

Several properties are herited from the network-theory (e.g., Citations Network are a 'directed' type of network)

**Turn cascading research into recursive-cascading-research.** Latter, codexplor will offer methods - not implemented yet - for realize a complete scanning of the packages used by a project as external dependancies : there will certainly be a recursive research of content on github between the 1st and the 2nd text-research of the cascading process, in order to get a complete corpus before to leave the step 1 to the step 2. 

