---
title: "get_text_network_from_files"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{get_text_network_from_files}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Assuming you have a bunch of path and/or url from a programming project, `codexplor::get_text_network_from_files()` made a cascading research. The returned network represents Citations Network of your *programming project* :

- the network is directed,
- indegrees of a node is 'how many functions of the project uses this precise func'. 
- Outdegree of a node is "how many functions of the project are used by this precise function". 
- ⟲ auto-mentioning typically reveal 'recursivity', once a func' call itself more than one times (1st mention is usually for define the func' name)

Under the hood, `codexplor::get_text_network_from_files()` will :

1. use `codexplor::srch_pattern_in_files_get_df()` to read  the files and realize a 1st text extraction. By default, the func' `get_text_network_from_files` read the content with `readlines` and extract every text *before* "<- function". This way, we have func' names as they are defined at the end of these 1st matches.

<!--1². a planned functionnality : recursive searching of files path^[Please note that an - optionnal - recursive package or library researches method' will be implemented here, after the 1st reading of the content since it's in the content that we will find stuff like package and other external depandancies.]-->

2. these matches are turned into a new pattern, and this pattern is searched in the content initially readed.

That's all : you have now turned your programming project into a 'Citations Network', by considering that the path of the files where a 2nd matches occur is the "from" part of an *edgelist*, and the files associated with the 1st matches are the "to" part of the *edgelist*. 

For example, giving a bunch of .R codes files path and/or url, you should first read all the content and get a network of func' :

    r_fls <- list.files(path = "~", ignore.case = T, all.files = T, full.names = T, recursive = T, pattern = ".R$")

    net <- codexplor::get_text_network_from_files(r_fls,   regex_to_exclude_files_path = "test-")
    # these func' are tunned for detecting R func' by default
    get_networkd3_from_igraph(codexplor::get_igraph_from_df(net) )

There is sometimes a false positive nodes that need to be excluded from the network. Typical "false positive" matches are the lines where you use the name of another function in a message, e.g. `cat("my_func() is deprecated. You should use this_function() instead)`. `get_text_network_from_files` offer several parameters for deal with your style of programming, if you really need to write functions names in other files than the ones that define the func'. 


